language: objective-c # OSX host

cache:
  directories:
    - monopkg/

env:
  - MONO_VERSION=3.2.4

install:
  - mkdir -p monopkg
  - cd monopkg
  - wget -c "http://download.mono-project.com/archive/${MONO_VERSION}/macos-10-x86/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg"
  - sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg" -target /
  - cd -

script:
  # Build
  - export EnableNuGetPackageRestore=true
  - xbuild /verbosity:quiet
  # Run Tests
  - mono ./packages/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./OpenTween.Tests/OpenTween.Tests.xunit
