language: c#

install:
  # for Mono 3.0
  - echo "deb http://debian.meebey.net/experimental/mono /" | sudo tee -a /etc/apt/sources.list

  - sudo apt-get update
  - sudo apt-get install --allow-unauthenticated mono-devel=3.0.1+dfsg-1~exp1~pre1 nunit-console
  # Install NUnit 2.6
  - wget -q http://de.archive.ubuntu.com/ubuntu/pool/main/n/nunit/libnunit2.6-cil_2.6.0.12051+dfsg-2_all.deb http://de.archive.ubuntu.com/ubuntu/pool/universe/n/nunit/nunit-console_2.6.0.12051+dfsg-2_all.deb
  - sudo dpkg -i libnunit2.6-cil_2.6.0.12051+dfsg-2_all.deb nunit-console_2.6.0.12051+dfsg-2_all.deb
  # Setup Xvfb
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

# Build
script:
  - xbuild /verbosity:quiet

# Run Tests
after_script:
  - nunit-console ./OpenTween.Tests/OpenTween.Tests.nunit

